### ISSUE TITLE
F# is not very suitable for writing a Roslyn-style compiler

### ISSUE THREAD

**Issue by kkshinkai** [chiyokyoko/sayalang#1]
We need a lot of circular references here. Do you plan to use the OOP part of the F#?

**Comment by chiyokyoko** [comment]
I don't  like C#, and I need .NET, at least give it a try.

Also, please don't use the OOP part in F# QAQ

**Comment by kkshinkai** [comment]
Ah, let me try, I'll give some examples later.

**Comment by chiyokyoko** [comment]
Omg, plz ccccccccccccccccchhhhhheck your email!

**Comment by chiyokyoko** [comment]
@kkshinkai  CHECK YOUR EMAIL!

**Comment by chiyokyoko** [comment]
> We need a lot of circular references here.

I realize that I don’t know how to translate APIs with a lot of circular references into functional language, any suggestion?

**Comment by kkshinkai** [comment]
> I realize that I don’t know how to translate APIs with a lot of circular references into functional language, any suggestion?

@chiyokyoko Example?

**Comment by chiyokyoko** [comment]
> > I realize that I don’t know how to translate APIs with a lot of circular references into functional language, any suggestion?
> 
> @chiyokyoko Example?

When recording source location information, the `Source` class needs to cache the `Line` information, and the `Line` class needs to record the reference of the `Source` for printing, both of which are necessary. What should I do?

**Comment by kkshinkai** [comment]
What you describe:

```fsharp
type Source = {
  Text: string;
  CachedLines: Line list;
}
type Line = {
  Source: Source;
  Start: int;
  End: int;
}

let print line = line.Source.Text.[line.Start...line.End]
```

What you need:

```fsharp
type Source = {
  Text: string;
}

type Line = {
  Start: int;
  End: int
  Text: string; // (*)
}
```

If you really care about the overhead, you need to take advantage of the persistence structure. I'm not familiar with F#, so I can't give you more advice. But be careful, strings on .NET are immutable but not persistent.

**Comment by kkshinkai** [comment]
We have made the decision, so this issue can be closed w

**Comment by kkshinkai** [comment]
We have made the decision, so this issue can be closed.
